### PR TITLE
Textual Revision of Motions

### LINKED ISSUE #5: A textual revision of the Motions is needed.
Things to change:

- In [16.2017.1](https://github.com/thewca/wca-documents/blob/master/documents/motions/16.2017.1%20-%20Disputes.md) it says "Ethical Committee" when the official name is "Ethics Committee".
- In [8.2018.1](https://github.com/thewca/wca-documents/blob/master/documents/motions/08.2018.1%20-%20Delegates.md) it was introduced "with copy to the WCA Board" but should it be "with a carbon copy (CC) to the Board" as in [10.2017.0](https://github.com/thewca/wca-documents/blob/master/documents/motions/10.2017.0%20-%20Committees%20and%20Teams.md)?
- ...

### PR DESCRIPTION
**Pull request by cubewhiz**
Fixes #5

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
Before merging this one we should go through all the other Motions in search of more typos or inconsistencies.

**Comment by cubewhiz** [comment]
Sure. I don't feel like re-reading all of our Motions and Bylaws, but I added two more that I came across.

**Comment by AlbertoPdRF** [comment]
I think we should do a throughout review after the Amendments we are planning to pass soon, so I propose to not merge this together with all the other changes that are being proposed now.

**Comment by AlbertoPdRF** [comment]
It seems to me like it will be easier to start fresh than to rebase this PR, so I'm closing it and pushing a new one!

**Pull request closed without merging**
