### PR TITLE
Added spanish translation for the judging tutorial

### PR DESCRIPTION
**Pull request by dmint789**
Added the spanish translation made by Gennaro Monetti for the judging tutorial.

### CODE REVIEW

**Review by notrichardpeng — APPROVED** [review]
LGTM

**Comment by dmint789** [comment]
My bad, there's a paging issue, I will fix it in a second

**Comment by dmint789** [comment]
It renders correctly now, I have checked the build. Please approve.

**Review by notrichardpeng — APPROVED** [review]

**Comment by notrichardpeng** [comment]
Oops I didn't check closely myself, yeah go ahead now :P

**Pull request merged**
