### PR TITLE
Fix Table in WCA Payment Authorization Policy

### PR DESCRIPTION
**Pull request by Nanush7**
Fixes: table not rendering + some columns go off the page.

### CODE REVIEW

**Comment by Nanush7** [comment]
The table now renders, but there is a different problem now:
Captura de pantalla 2024-09-20 a la(s) 11 30 23

**Comment by EdHollingdale** [comment]
What if in the table we change "Championships" to "Champ." and "Equipment" to "Equip."?

**Comment by Nanush7** [comment]
Fixed!

Captura de pantalla 2024-09-20 a la(s) 13 18 31

**Review by dmint789 — APPROVED** [review]
LGTM!

**Comment by EdHollingdale** [comment]
@thewca/software-team are you able to review this and merge?

**Comment by nsilvestri** [comment]
Hi Ed, I don't believe WST approval is required here. You are good to merge.

**Comment by Nanush7** [comment]
We (at least WQAC members) do need WST approval to merge. Github won't let us otherwise.

**Comment by nsilvestri** [comment]
Ope, that's an issue with CODEOWNERS. I'll see if I can get that resolved.

**Pull request merged**
