### PR TITLE
Fix broken document links

### LINKED ISSUE #376: Broken links for some documents
`wca{...}` is always replaced with the www subdomain, but in some cases it needs to be replaced with the documents subdomain. Maybe the script can check if the url includes "documents/" and then decide which one to use? (this way we don't need to change every single file where `wca{...}` is used).

The list of files using this shortcut:
```
$ grep -R --files-with-matches "wca{"
./documents-guide.md
./bin/build.sh
./README.md
./documents/motions/10.2021.6 - Financial Committee.md
./documents/motions/07.2021.1 - Registered Speedcubers.md
./documents/motions/01.2021.1 - Spirit.md
./documents/motions/04.2022.1 - WCA Board.md
./documents/motions/10.2021.2 - Competition Announcement Team.md
./documents/motions/19.2021.1 - Regulations and Guidelines.md
./documents/motions/10.2021.9 - Regulations Committee.md
./documents/motions/10.2022.3 - Disciplinary Committee.md
./documents/policies/external/Competition Requirements.md
./documents/policies/external/Logo Usage.md
./documents/Code of Ethics.md
```

### PR DESCRIPTION
**Pull request by dmint789**
Fixes #376

- Add wcadoc{} shortcut that inserts a link to documents.worldcubeassociation.org
- Fix all broken links related to the move of documents to the `documents` subdomain
- Fix broken link from CoE to Spirit motion
- Fix broken link from Disciplinary Committee motion to Suspensions and Other Sanctions motion

### CODE REVIEW

**Comment by dmint789** [comment]
@thewca/software-team please approve, this is urgent.

**Comment by dmint789** [comment]
I have downloaded the build and made sure that every single affected link works correctly now.

**Comment by Nanush7** [comment]
@dmint789 the Regulations are still accessible through the www subdomain.

**Review by dunkOnIT — APPROVED** [review]

**Review by nsilvestri — APPROVED** [review]
lgtm

**Review by lnzainn — APPROVED** [review]

**Review by lnzainn — APPROVED** [review]
LGTM

**Review by Epride — APPROVED** [review]

**Pull request merged**
