### PR TITLE
Competition templates

### PR DESCRIPTION
**Pull request by denthebro**
Readme file for WCA competition organization templates

### CODE REVIEW

**Review by c-goodyear — APPROVED** [review]
Board approved.

**Comment by denthebro** [comment]
> Board approved.

Thank you, but merging is still blocked unfortunately. Looks like I need @Epride to approve too.

**Comment by c-goodyear** [comment]
> > Board approved.
> 
> Thank you, but merging is still blocked unfortunately. Looks like I need @Epride to approve too.

You need Software, not Ethan.

**Review by gregorbg — APPROVED** [review]
There we go :) Please use the "squash and merge" option and we should be good!

**Pull request merged**
