### PR TITLE
Add table of contents to Delegate Crash Course

### PR DESCRIPTION
**Pull request by Nanush7**
I hope this is what you were looking for. :)

Let me know if you want me to change the place of the table of contents or the placement of the sub-items in the list.

I tested it on Brave (latest stable) and Okular (from KDE).

### CODE REVIEW

**Comment by dmint789** [comment]
Would it not be better to have the table of contents above "On the Delegate candidateship" (so on the first page) and have that item included in the table of contents?

**Review by dmint789 — CHANGES_REQUESTED** [review]
For some reason the links to the different sections don't work in the rendered document, although I'm pretty sure they worked before this commit

**Comment by Nanush7** [comment]
The problem seems to be in Firefox; It still works well for me in Brave and Okular. Which PDF viewer are you using?

**Comment by nsilvestri** [comment]
Did some investigation of my own. Chrome works fine. Firefox (116.0.3, Windows 11) definitely has some issues, as some of the links work, but not all. I don't see any pattern between the links that do work and the ones that don't:

- On the Delegate candidateship ❌
    - The roles of a WCA Delegate ✅
    - General Advice ✅
- On accepting to delegate a competition ❌
- Requesting a competition ✅
    - Some general rules about requesting a competition ❌
    - How to fill out the new competition page ❌
    - Adding events and a schedule ❌
    - Requesting a Fewest Moves Simultaneous Competition ❌
    - Making changes to an existing competition ❌
- Administering competition results ❌
    - Preparation and score taking tools ❌
    - Administering registration data ❌
    - Scoretaking during the competition ❌
    - Checking competition results before submission ❌
    - Compiling Competition Results ❌
    - Submitting competition results ✅
    - Requesting changes to competition results ❌
- Requesting changes to person data ❌
- On submitting competition reports ❌
- Paying competition Dues ✅
- Administering WCA user accounts ❌
    - Handling WCA-ID claim requests ❌
- Acquiring competition equipment ❌
- Recommending a Delegate ✅
- Important Links ✅

Looking at the links more closely, the build tool seems to be mangling the links into URL-encodings, or perhaps Firefox is mangling their interpretation:

"On the Delegate candidateship" link: `/home/nick/code/wca-documents/build/edudoc/delegate-crash-course/delegate_crash_course.pdf#%DA%12%BC%D4%FF%20%3B%u02C7Q%08y6%7Fm%BAj%EF%B7Ri`

"The roles of a WCA Delegate" link: `/home/nick/code/wca-documents/build/edudoc/delegate-crash-course/delegate_crash_course.html%23the-roles-of-a-wca-delegate`

**Comment by Nanush7** [comment]
Yeah, I also couldn't find any pattern. I tried to add page breaks but it didn't get any better. I will have a look at bugzilla next week.

**Pull request closed without merging**
