### PR TITLE
Add Armenian translation of the judge tutorial

### PR DESCRIPTION
**Pull request by dmint789**
This PR adds the Armenian translation of the judge tutorial made by Mayis Jraghatspanyan

### CODE REVIEW

**Comment by dmint789** [comment]
I think that was the final force push, the output file looks right. Please approve.

**Comment by gregorbg** [comment]
Do we have any review of whether his translation is correct? There are no verified translators for `am` on the website currently...

**Comment by dmint789** [comment]
We do not. I read the translation back into English using Google Translate and it seems to check out, although this method obviously does not convey certain nuances of language.

**Comment by DanielEgdal** [comment]
Given Deni has checked it through google translate, and Mayis has been a listed organiser for 100% of the competitions in his country I think this is enough verification that the translation is suitable for the website.

**Review by gregorbg — APPROVED** [review]
I consider Daniel's post above as an approval.
Let's see if our build toolchain can handle Armenian Unicode! :smile:

**Pull request merged**
