### PR TITLE
Update Educational Resources

### PR DESCRIPTION
**Pull request by dmint789**
CRITICAL TO-DO: Update all links to the wca website.

1. Add image source files
2. Update timers to reflect the newest (gen 5) version
3. Remake the scorecard image in the competitor tutorial from scratch and include scrambler signatures in it
4. Add missing translation update for the Portuguese competitor guide
5. Rename some image files for consistency

### CODE REVIEW

**Comment by Nanush7** [comment]
We also need to update several links. Do you want to do it here?

**Comment by dmint789** [comment]
@Nanush7 could you give me a list of links that need to be fixed? Or would the list be too long?

**Comment by Nanush7** [comment]
You can do a search and replace for links marching "https://www.worldcubeassociation.org/documents/*" and "https://www.worldcubeassociation.org/edudoc/*". Just change the www to documents, the rest of the url is the same.

**Comment by dmint789** [comment]
When was this subdomain added? Is this a new thing? In any case, I can open a new PR for this, since this is a very different scope.

**Comment by Nanush7** [comment]
I can open one if you want, but we should merge this one first.

Yes, the WST migrated the documents recently.

**Comment by dmint789** [comment]
That would be helpful, thank you

**Pull request merged**
