### PR TITLE
Add Armenian translation of the competitor tutorial and clean up the translations for this document

### PR DESCRIPTION
**Pull request by dmint789**
This PR does two things: add the Armenian translation of the competitor tutorial made by Mayis Jraghatspanyan and clean up the folder for this document and all of its translations. Another minor thing is that I appended one line in the main doc to give credit to Gennaro Monetti for his translation into Spanish, which was not done at the time.

I strongly believe that this clean-up needed to happen for a while, because the more translations we add, the messier our document folders become. There were also some things that were just inconsistent in this specific folder. I intend to do this simple clean-up for the other edudocs that have translations at a later date, but for this PR only the competitor tutorial folder was changed.

Here are all of the changes that will be felt by the users:
This link is added: https://worldcubeassociation.org/edudoc/competitor-tutorial/am/tutorial.pdf
This link: https://worldcubeassociation.org/edudoc/competitor-tutorial/tutorial_es.pdf moves here: https://worldcubeassociation.org/edudoc/competitor-tutorial/es/tutorial.pdf
This link: https://worldcubeassociation.org/edudoc/competitor-tutorial/tutorial_se.pdf moves here: https://worldcubeassociation.org/edudoc/competitor-tutorial/se/tutorial.pdf
I believe the changes to the links for the Swedish and Spanish translations are worthy sacrifices, as the new links can be found in the main English document anyways, and the link for that document remains the same. If necessary, I could add custom routes to the main website that would redirect the old links to the new ones.

Lastly, there are plenty of image changes in this PR. Please ignore these, they are simply better renders of the same content with one exception: I removed the line from cover infographic that gives credit to me and Tom Nelson, as that one line means we have to edit this image separately for this document, when we could just omit it and use the exact same image as the one used in the competition templates project. This same credit is given in the readme for that project anyways.

I know this is a significant update and I am welcome to suggestions.

### CODE REVIEW

**Comment by dmint789** [comment]
That should be the last commit

**Review by DanielEgdal — DISMISSED** [review]
lgtm

**Comment by dmint789** [comment]
Some changes have been made to the translation, please approve

**Review by DanielEgdal — APPROVED** [review]
internal discussion done. lgtm still

**Pull request merged**
