### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by gregorbg**

### CODE REVIEW

**Comment by denthebro** [comment]
The documents won't need to be updated in any way after this migration, right? It will just continue to produce the pdf files just like Travis used to?

**Comment by gregorbg** [comment]
Yes, correct. It is simply a drop-in replacement for Travis.

**Comment by gregorbg** [comment]
Note to WST: You can verify under `Settings > Secrets` that the private key `DEPLOY_PRIVATE_KEY` is installed as repository secret.

**Comment by gregorbg** [comment]
Merging now, as this is blocking a whole lot of other stuff (and chances are I will have to adjust this anyways)

**Pull request merged**
