### PR TITLE
Small edits to the Competition safety policy

### PR DESCRIPTION
**Pull request by denthebro**
Added 4 periods and fixed 1 sentence

### CODE REVIEW

**Comment by denthebro** [comment]
Second commit is related to this issue: https://github.com/thewca/wca-documents/issues/197

**Comment by Epride** [comment]
For the competition safety policy the Board discusses changes every two weeks and we draft our thoughts into one document and then create a single PR to make the voting for amendment easier. As such could you leave your suggestions as issues, this is easier for us to handle.

Also the way Bylaws and Policies are handled are different so they defiantly should not be in the same PR

**Comment by denthebro** [comment]
@Epride should I redo this PR as an issue and a PR for the bylaws change then?

**Comment by c-goodyear** [comment]
This is being handled in #232 now and avoids the edits you made to the By-laws causing issues.

**Pull request closed without merging**
