### PR TITLE
Fix spelling errors/typos

### PR DESCRIPTION
**Pull request by JonEsparaz**
- Fixes spelling errors in Competitor Tutorial and Organizer Guidelines
- Fixes typo in Delegate Crash Course (`malto` vs `mailto`)

### CODE REVIEW

**Comment by denthebro** [comment]
Please hold off on this PR until the builder is updated. This should be finished soon.

**Comment by Epride** [comment]
The errors in the motions will need to be fixed in the next amendment which likely wont be occurring until later this year or early next. As such we won't be able to merge those in this PR.

For the educational documents best to send WQAC (wqac@worldcubeassociation.org) an email about these and they should be able to fix them up fairly easily.

**Comment by JonEsparaz** [comment]
Only the changes for the educational documents are in the PR now - I'll contact the WQAC about this.

I've opened an issue for the errors in the motions: https://github.com/thewca/wca-documents/issues/247.

**Review by gregorbg — APPROVED** [review]
LGTM from a technical perspective. As soon as @thewca/wqac gives their consent, we can merge.

**Comment by DanielEgdal** [comment]
When WQAC got the email about the topic, we noted internally (sorry for not responding...) that there were some portions of the PR might conflict with other changes (I think this was the concern https://github.com/thewca/wca-documents/pull/244/). The changes in crash-course is something that WQAC will additional have to update in our WIP document. When the other mentioned PR is merged, and if there is no conflict, then I think this can be merged.

**Comment by denthebro** [comment]
#244 has been merged now and there are no conflicts. LGTM

**Comment by JonEsparaz** [comment]
@gregorbg good to merge?

**Pull request merged**
